
export * from "../pages/about-us/about-us.component"
export * from "../pages/agents/agents.component"
export * from "../pages/blogs/blogs.component"
export * from "../pages/properties/properties.component"
export * from "../pages/contact/contact.component"
export * from "../pages/profile/profile.component"
export * from "../pages/inspirations/inspirations.component"
export * from "../pages/trending/trending.component"
export * from "../pages/designs-view/designs-view.component"
export * from "../pages/add-review/add-review.component"
export * from "../pages/designer-view/designer-view.component"
export * from "../pages/home-designers/home-designers.component"
export * from "../pages/home-designs/home-designs.component"
export * from "../pages/home-blogs/home-blogs.component"
export * from "../pages/design-card/design-card.component"